### ISSUE TITLE
Game crashes when Discord is closed.

### ISSUE THREAD

**Issue by BubbaJuice** [DeDiamondPro/HyCord#14]
Problem: You have Minecraft open and Discord closed. You try and join a server. The game crashes and the Discord client opens.
What I think should be happening: The game does not crash and the client still opens.

I am using the latest prerelease from this GitHub page. I am using Discord Canary. I am on Windows 10.

**Comment by isXander** [comment]
A crash report would be useful...

**Comment by BubbaJuice** [comment]
Here is the log. It was made with only the Hychat mod in my mods folder. No crash report was generated.
[latest.log](https://github.com/DeDiamondPro/HyCord/files/6580895/latest.log)

**Comment by DeDiamondPro** [comment]
Known, I’m looking for a way to fix it without causing nullpointerexeptions, if this really bothers you try using a stable release, it shouldn’t have it.

**Comment by DeDiamondPro** [comment]
Fixed in 1.2.0-pre4.3
