### ISSUE TITLE
Weird bug causing me to be in 2 servers at once

### ISSUE THREAD

**Issue by itsbumble** [DeDiamondPro/HyCord#8]
when I log out of another server and log into hypixel, the chat and tablist are still from the other server, effectively making me logged into 2 servers. Also sometimes my log file gets spammed a crap ton. to put it simply it's like the disconnect button just doesnt work

Log file: https://hst.sh/ejepibiwex.pl
Screenshots: 
https://imgur.com/7PdqjXT (hide players on, every one of these players is from the other server)
https://imgur.com/a/IaPgyIt (chat messages from bedwarspractice.club on Hypixel)

**Comment by DeDiamondPro** [comment]
Log spam is not hycord and is caused my something from multimc, for the rest I will investigate after school

**Comment by itsbumble** [comment]
I think the log spam is actually hycord since multimc usually throws some onesixlauncher stuff at the bottom of errors.

**Comment by DeDiamondPro** [comment]
Can you tell me what version you are using?

**Comment by itsbumble** [comment]
1.2.0 pre2.2

**Comment by DeDiamondPro** [comment]
Log spam and disconnect thingy are releated, working on a fix now

**Comment by DeDiamondPro** [comment]
Fixed in 1.2.0-pre2.3, I will now investigate if this also occurs on stable releases
